version: '3.8'

services:
  postgres:
    container_name: sig-usuario
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sig-usuario